[package]
name = "tiledb-rust"
version = "0.1.0"
authors = ["Bogdan State <bogdan@scie.nz>"]
edition = "2018"
links = "tiledb"

[dependencies]
bindgen = "0.58.1"
libc = "0.2.95"

[build-dependencies]
bindgen = "0.58.1"
